my-guix: python-uinput: Update to 1.0.1.
Previously, attempting to build python-uinput with the 'sanity-check' phase
resulted in the following error:

ImportError: dynamic module does not define module export function (PyInit__libsuinput)

The included patch adds the expected module initialization function.

* files/patches/0001-libsuinput-Add-module-initialization-function.patch: New
patch.
* modules/my-guix/packages/keyboard-center.scm (python-uinput): Update to
1.0.1.
[origin]: Add patch to fix 'sanity-check' phase.
[arguments]<#:phases>: Add phase 'patch-libudev to fix libudev not being
found.